---
title: "conditionals_loops"
format: html
---

```{r}
# Value representing Particulate Matter 2.5
pm2_5 <- 180

if (pm2_5 < 100){
  print("Low to moderate risk")
} else if (pm2_5 >= 100 & pm2_5 < 150){
  print("Unhealthy for sensitive groups")
} else if  (pm2_5 >= 150) {
  print("Health risk present")
}
```

```{r}
species <- "gray whale"

#detects when a pattern is present
#stringr::str_detect(species, pattern = "whale")

if (stringr::str_detect(species, "whale")){
  print("You found a whale!")
}
```

```{r}
base_burrito <- 6.50

main_ingredient <- c("veggie", "chicken", "steak")

main_ingredient <- "steak"
  if (main_ingredient == "veggie"){
    print(paste("$", base_burrito[1]))
  } else if (main_ingredient == "chicken"){
    print(paste("$", base_burrito[1]+3))
  } else if(main_ingredient == "steak"){
    print(paste("$", base_burrito[1]+3.25))
  }
    
  

```
```{r}
fish <- c("goldfish" = 8, "tetras" = 10,"guppies" = 12, "mollies" = 23)
#species <-c("goldfish", "tetras", "guppies", "mollies")

#total_fish <- (8 + 10 + 12 + 23)

for (i in seq_along(fish)){
  prop_fish <- fish[i] / sum(fish)
  print(prop_fish)
}

```

```{r}
month.name

for (i in seq_along(month.name)){
  print (paste(month.name[i], "is month", i))
}
```

